site_name: CDE — Chemical Discovery Engine
site_description: Documentation for the Chemistry Discovery Engine

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.blocks.details
  - pymdownx.blocks.admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js



nav:
  - Home: index.md

  - User Guide:
      - Overview: user-guide/index.md
      - Compilation and setup: user-guide/setup.md
      - Annotated input: user-guide/annotated-input.md
      - Structure formats: user-guide/formats.md
      - PES calculations: user-guide/pes.md
      - PES templates: user-guide/pes-templates.md
      - Move-file format: user-guide/move-files.md
    #   - Forbid Files: user-guide/forbid-files.md
      - Hints: user-guide/hints.md
      - References: user-guide/references.md

  - Tutorials:
      - Overview: tutorials/index.md
      - Tutorial 1 — CINEB: tutorials/cineb.md
      - Tutorial 2 — CINEB + LAMMPS: tutorials/cineb-lammps.md
      - Tutorial 3 — Path Finding: tutorials/pathfind.md
      - Tutorial 4 — Advanced Path Finding: tutorials/pathfind-advanced.md
      - Tutorial 5 — Network Growth: tutorials/netgrow.md
      - Tutorial 6 — Breakdown: tutorials/breakdown.md

  - API Reference:
      - Overview: api/index.md

